// Turns the garden notes' yard map (design/front-yard-map.json in GARDEN_DIR) into
// one SQL transaction for a garden that's already loaded:
//
//   npm run load:map -- <garden-id>
//
// - gardens.map gets the drawing: lot, house, driveways, trees, water, beds, and each
//   site's outline keyed by site number.
// - A site on the map that the garden doesn't have yet is added (number and name).
// - sites.existing gets the plants already growing there, from the notes.
//
// Writes scripts/private/load-map.sql (git-ignored). Like load-garden.mjs, this repo
// never connects to the shared database: the SQL is run as the service role. Running
// it again replaces the map and the existing-plant lists; nothing else is touched.

import fs from 'node:fs'
import path from 'node:path'

const gardenId = process.argv[2]
if (!/^[0-9a-f-]{36}$/.test(gardenId ?? '')) throw new Error('Pass the garden id: npm run load:map -- <garden-id>')
const dir = process.env.GARDEN_DIR
if (!dir) throw new Error('Set GARDEN_DIR in .env.local')

const map = JSON.parse(fs.readFileSync(path.join(dir, 'design', 'front-yard-map.json'), 'utf8'))
const outPath = path.resolve('scripts/private/load-map.sql')

const text = (v) => (v == null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const texts = (a) => (a?.length ? `array[${a.map(text).join(', ')}]::text[]` : `'{}'::text[]`)
const G = `'${gardenId}'::uuid`

// The drawing goes in gardens.map; the plant lists go in sites.existing.
const drawing = {
  ...map,
  sites: Object.fromEntries(Object.entries(map.sites).map(([n, s]) => [n, { d: s.d, label: s.label }])),
}

const sites = Object.entries(map.sites).map(([n, s]) => ({ number: Number(n), name: s.name, existing: s.existing ?? [] }))

const sql = `-- Generated by scripts/load-map.mjs from front-yard-map.json (${map.source}).
begin;

do $$
begin
  if not exists (select 1 from garden.gardens where id = ${G}) then
    raise exception 'No garden with id ${gardenId}';
  end if;
end $$;

update garden.gardens set map = ${text(JSON.stringify(drawing))}::jsonb where id = ${G};

insert into garden.sites (garden_id, number, name) values
${sites.map((s) => `  (${G}, ${s.number}, ${text(s.name)})`).join(',\n')}
on conflict (garden_id, number) do nothing;

${sites.map((s) => `update garden.sites set existing = ${texts(s.existing)} where garden_id = ${G} and number = ${s.number};`).join('\n')}

commit;

select
  (select jsonb_array_length(coalesce(map -> 'trees', '[]')) from garden.gardens where id = ${G}) as trees,
  (select count(*) from jsonb_object_keys((select map -> 'sites' from garden.gardens where id = ${G}))) as mapped_sites,
  (select count(*) from garden.sites where garden_id = ${G}) as sites,
  (select count(*) from garden.sites where garden_id = ${G} and cardinality(existing) > 0) as sites_with_existing;
`

fs.writeFileSync(outPath, sql)
console.log(`Wrote ${path.relative(process.cwd(), outPath)}`)
console.log(
  `Expect: trees ${map.trees.length}, mapped_sites ${sites.length}, sites ${sites.length} or more, ` +
    `sites_with_existing ${sites.filter((s) => s.existing.length).length}`,
)
