// Turns the import (scripts/private/garden-import.json) into one SQL transaction that
// loads it into a garden that already exists (PLAN.md, build step 2).
//
//   npm run load:garden -- <garden-id>
//   npm run load:garden -- --catalogue     (catalogue only, for a garden already loaded)
//
// Writes scripts/private/load-garden.sql (git-ignored). This repo never connects to the
// shared database: the SQL is run by whoever manages that project, as the service role.
//
// - The catalogue (plants, nurseries, tag rules) is shared, so rows already there by key
//   are left as they are.
// - Everything else belongs to the garden. The transaction stops without changing
//   anything if the garden is missing or already has sites, plan items or tasks, so it
//   can't load twice.

import fs from 'node:fs'
import path from 'node:path'

// --catalogue adds plants, nurseries and tag rules that aren't there yet, and touches no
// garden. That's how the rest of the ranking was added after the first load.
const catalogueOnly = process.argv[2] === '--catalogue'
const gardenId = catalogueOnly ? '00000000-0000-0000-0000-000000000000' : process.argv[2]
if (!/^[0-9a-f-]{36}$/.test(gardenId ?? ''))
  throw new Error('Pass the garden id, or --catalogue: npm run load:garden -- <garden-id>')

const data = JSON.parse(fs.readFileSync(path.resolve('scripts/private/garden-import.json'), 'utf8'))
const outPath = path.resolve('scripts/private/load-garden.sql')

// ---------- SQL literals ----------

const text = (v) => (v == null || v === '' ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const num = (v) => (v == null ? 'null' : String(Number(v)))
const bool = (v) => (v ? 'true' : 'false')
const months = (a) => `'{${(a ?? []).map(Number).join(',')}}'::smallint[]`
const texts = (a) => (a?.length ? `array[${a.map(text).join(', ')}]::text[]` : `'{}'::text[]`)
const G = `'${gardenId}'::uuid`
const plantId = (key) => `(select id from garden.plants where key = ${text(key)})`
const nurseryId = (key) => (key == null ? 'null' : `(select id from garden.nurseries where key = ${text(key)})`)
const siteId = (n) => (n == null ? 'null' : `(select id from garden.sites where garden_id = ${G} and number = ${num(n)})`)

const rows = (list, fn) => list.map((x, i) => `  (${fn(x, i).join(', ')})`).join(',\n')

// ---------- statements ----------

const sql = []

sql.push(`-- Generated by scripts/load-garden.mjs from garden-import.json (${data.generated_at}).
begin;

do $$
begin
  if not exists (select 1 from garden.gardens where id = ${G}) then
    raise exception 'No garden with id ${gardenId}';
  end if;
  if exists (select 1 from garden.sites where garden_id = ${G})
     or exists (select 1 from garden.plan_items where garden_id = ${G})
     or exists (select 1 from garden.tasks where garden_id = ${G}) then
    raise exception 'This garden already has sites, plan items or tasks; not loading twice';
  end if;
end $$;`)

sql.push(`-- Catalogue: plants
insert into garden.plants (key, common, latin, kind, native, tags, plant_months, bloom_months, pollinator_months, threat_tier, threat_reason, rank, why) values
${rows(data.plants, (p) => [
  text(p.key), text(p.common), text(p.latin), text(p.kind), bool(p.native), texts(p.tags),
  months(p.plant_months), months(p.bloom_months), months(p.pollinator_months),
  text(p.threat?.tier), text(p.threat?.reason), num(p.rank), text(p.why),
])}
on conflict (key) do nothing;`)

sql.push(`-- Catalogue: nurseries
insert into garden.nurseries (key, name, category, url, location, notes, last_checked) values
${rows(data.nurseries, (n) => [
  text(n.key), text(n.name), text(n.category), text(n.url), text(n.location), text(n.notes),
  n.last_checked ? `${text(n.last_checked)}::date` : 'null',
])}
on conflict (key) do nothing;`)

const tagRules = data.rules.filter((r) => r.scope === 'tag')
const gardenRules = data.rules.filter((r) => r.scope === 'site' || r.scope === 'garden')
const otherRules = data.rules.filter((r) => !['tag', 'site', 'garden'].includes(r.scope))
if (otherRules.length) throw new Error(`Rules with a scope this loader doesn't know: ${otherRules.map((r) => r.scope).join(', ')}`)

// Catalogue rules have no key; skip any already there with the same tag, topic and text.
sql.push(`-- Catalogue: rules about a tag
insert into garden.rules (topic, verdict, text, tag, source)
select v.topic, v.verdict, v.text, v.tag, v.source
from (values
${rows(tagRules, (r) => [text(r.topic), text(r.verdict), text(r.text), text(r.target), text(r.source)])}
) as v (topic, verdict, text, tag, source)
where not exists (
  select 1 from garden.rules r
  where r.garden_id is null and r.tag = v.tag and r.topic = v.topic and r.text = v.text
);`)

sql.push(`-- The garden: sites
insert into garden.sites (garden_id, number, name, conditions, notes) values
${rows(data.sites, (s) => [G, num(s.number), text(s.name), text(s.conditions), text(s.notes)])};`)

sql.push(`-- The garden: rules about the whole garden or one site
insert into garden.rules (topic, verdict, text, garden_id, site_id, source) values
${rows(gardenRules, (r) => [
  text(r.topic), text(r.verdict), text(r.text), G, r.scope === 'site' ? siteId(r.target) : 'null', text(r.source),
])};`)

sql.push(`-- The garden: plan items
insert into garden.plan_items (garden_id, plant_id, site_id, season, status, qty_min, qty_max, nursery_id, spot, notes, source) values
${rows(data.plan_items, (p) => [
  G, plantId(p.plant), siteId(p.site), text(p.season), text(p.status), num(p.qty_min), num(p.qty_max),
  nurseryId(p.nursery), text(p.where), text(p.notes), text(p.source),
])};`)

// Keep each month's tasks in the schedule's order.
const position = {}
const tasks = data.tasks.map((t) => ({ ...t, position: (position[t.month] = (position[t.month] ?? -1) + 1) }))
const repeating = data.recurring_tasks ?? []
const unknownRepeat = repeating.filter((t) => t.every !== 'month')
if (unknownRepeat.length) throw new Error(`Repeating tasks this loader doesn't know: ${unknownRepeat.map((t) => t.every).join(', ')}`)

sql.push(`-- The garden: monthly tasks
insert into garden.tasks (garden_id, section, title, link, month, every_month, position, source) values
${rows(tasks, (t) => [G, text(t.section), text(t.title), text(t.link), num(t.month), 'false', num(t.position), text(t.source)])};`)

if (repeating.length) {
  sql.push(`-- The garden: tasks that repeat every month
insert into garden.tasks (garden_id, section, title, detail, month, every_month, position) values
${rows(repeating, (t, i) => [G, text(t.section), text(t.title), text(t.detail), 'null', 'true', num(i)])};`)
}

// The counts come back as the last result, so whoever runs it can compare with the import.
sql.push(`commit;

select
  (select count(*) from garden.sites where garden_id = ${G}) as sites,
  (select count(*) from garden.rules where garden_id = ${G}) as garden_rules,
  (select count(*) from garden.rules where garden_id is null) as catalogue_rules,
  (select count(*) from garden.plan_items where garden_id = ${G}) as plan_items,
  (select count(*) from garden.tasks where garden_id = ${G} and not every_month) as monthly_tasks,
  (select count(*) from garden.tasks where garden_id = ${G} and every_month) as repeating_tasks,
  (select count(*) from garden.plants) as plants,
  (select count(*) from garden.nurseries) as nurseries;`)

if (catalogueOnly) {
  const catalogue = [
    `-- Generated by scripts/load-garden.mjs --catalogue from garden-import.json (${data.generated_at}).\nbegin;`,
    ...sql.filter((s) => s.startsWith('-- Catalogue')),
    `commit;

select
  (select count(*) from garden.plants) as plants,
  (select count(*) from garden.plants where rank is not null) as ranked_plants,
  (select count(*) from garden.nurseries) as nurseries,
  (select count(*) from garden.rules where garden_id is null) as catalogue_rules;`,
  ]
  const cataloguePath = path.resolve('scripts/private/load-catalogue.sql')
  fs.writeFileSync(cataloguePath, catalogue.join('\n\n') + '\n')
  console.log(`Wrote ${path.relative(process.cwd(), cataloguePath)}`)
  console.log(
    `Expect at most: plants ${data.plants.length}, ranked_plants ${data.plants.filter((p) => p.rank).length}, ` +
      `nurseries ${data.nurseries.length}, catalogue_rules ${tagRules.length} (rows already there are kept)`,
  )
  process.exit(0)
}

fs.writeFileSync(outPath, sql.join('\n\n') + '\n')
console.log(`Wrote ${path.relative(process.cwd(), outPath)}`)
console.log(
  `Expect: sites ${data.sites.length}, garden_rules ${gardenRules.length}, catalogue_rules ${tagRules.length}, ` +
    `plan_items ${data.plan_items.length}, monthly_tasks ${tasks.length}, repeating_tasks ${repeating.length}, ` +
    `plants ${data.plants.length}, nurseries ${data.nurseries.length} (catalogue counts on a first load)`,
)
